#!/usr/bin/with-contenv sh

umask 022

if [ -z "$REMOTE_MOUNT" ]; then
  echo "Error: REMOTE_MOUNT environment variable was not passed to the container."
  exit 1
fi

mount_command="rclone mount --config=/config/.rclone.conf $RCLONE_MOUNT_OPTIONS $REMOTE_MOUNT /data"

echo "Executing => $mount_command"
exec \
	s6-setuidgid abc $mount_command